context:
  ami: "ami-0454bb2fefc7de534"
  
ami: "${ami}"

remote_states:
  "vpc":
      organization: "devfloors"
      workspace: "terraform-k8s-boilerplate"

instance_name: "test-private-ec2"
security_group_name: "test-private-ec2-sg"
key_name: "panki-dev"
